// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

[PrimaryKey("AccountId", "RoleId")]
[Table("AccountRole")]
public partial class AccountRole
{
    [Key]
    public int AccountId { get; set; }

    [Key]
    public int RoleId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("AccountRoles")]
    public virtual Role Role { get; set; } = null!;
}