// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

[Table("Consultation")]
public partial class Consultation
{
    [Key]
    public int ConsultationId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }
    [Required]
    [StringLength(100)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    [Required]
    [StringLength(150)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    public DateTime Date { get; set; }

    public bool Status { get; set; }

    public int? EmployeeId { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Consultations")]
    public virtual Employee Employee { get; set; }
}