// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

[Table("Customer")]
public partial class Customer
{
    [Key]
    public int CustomerId { get; set; }

    [StringLength(250)]
    public string FullName { get; set; } = null!;

    public bool? Gender { get; set; }

    [StringLength(50)]
    public string? Phone { get; set; }

    public DateOnly? DoB { get; set; }

    [StringLength(250)]
    public string? Address { get; set; }

    [StringLength(150)]
    public string Email { get; set; } = null!;

    public int AccountId { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [ForeignKey("CustomerId")]
    [InverseProperty("Customers")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}