// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(250)]
    public string FullName { get; set; }

    public bool Gender { get; set; }

    public DateOnly DoB { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Required]
    [StringLength(250)]
    public string Address { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    public bool? IsDelete { get; set; }

    public int AccountId { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Employees")]
    public virtual Account Account { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Consultation> Consultations { get; set; } = new List<Consultation>();

    [InverseProperty("Employee")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Employee")]
    public virtual ICollection<OrderService> OrderServices { get; set; } = new List<OrderService>();

    [InverseProperty("Employee")]
    public virtual ICollection<ResponseFeedback> ResponseFeedbacks { get; set; } = new List<ResponseFeedback>();
}