// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

public partial class News
{
    [Key]
    public int NewsId { get; set; }

    [StringLength(100)]
    public string Title { get; set; } = null!;

    public string Content { get; set; } = null!;

    public DateOnly DatePosted { get; set; }

    public int? ImageId { get; set; }

    public int EmployeeId { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("News")]
    public virtual Employee Employee { get; set; } = null!;

    [ForeignKey("ImageId")]
    [InverseProperty("News")]
    public virtual Image? Image { get; set; }
}