// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetStoreProject.Models;

public partial class News
{
    [Key]
    public int NewsId { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    public DateOnly DatePosted { get; set; }

    public int? TagId { get; set; }

    [StringLength(250)]
    public string Summary { get; set; }

    public bool? IsDelete { get; set; }

    public int EmployeeId { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("News")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("News")]
    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    [ForeignKey("TagId")]
    [InverseProperty("News")]
    public virtual TagNews Tag { get; set; }
}